name: CMake

on:
  # Run when asked manually and on PRs, running on every push/commit will create lots of queued up workflows
  workflow_dispatch:
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
        # 2 Ubuntus is more than enough and will test general Linux coverage, while not taking multiple days to finish

    steps:
    - uses: actions/checkout@main
    
    - name: Update with apt
      run: sudo apt update
    - name: Install dependencies with apt
      run: sudo apt -y install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
